decide version number by date

diff --git a/install_llvm b/install_llvm
--- a/install_llvm
+++ b/install_llvm
@@ -1,13 +1,38 @@
 #!/usr/bin/env bash
-# Usage: bash install_llvm
+# Usage: bash install_llvm [VERSION_NUMBER]
+# N.B.: VERSION_NUMBER is used only on Linux; on macOS, Homebrew will always install the latest
+# version of LLVM as of 2026.
+# If VERSION_NUMBER is not provided, the script will determine the version number based on the
+# current date and the LLVM release schedule, which is updated every six months as of 2026, in
+# March and September. The version number in September 2025 is 21.
 
 
-VERSION_NUMBER="21"
+if [[ $# -eq 1 ]]; then
+    VERSION_NUMBER=$1
+elif [[ $# -eq 0 ]]; then
+    # According to "LLVM Release Schedule" at https://llvm.org, we assume that the version is
+    # updated every six months, in March and September. The version number in September 2025 is 21.
+    # Then we can calculate the version number by the formula:
+    # VERSION_NUMBER = 21 + (CURRENT_YEAR - 2025) * 2 + (CURRENT_MONTH >= 9 ? 1 : 0).
+    CURRENT_YEAR=$(date +%Y)
+    CURRENT_MONTH=$(date +%m)
+    echo "Current year: ${CURRENT_YEAR}, current month: ${CURRENT_MONTH}"
+    if [[ ${CURRENT_MONTH} -ge 9 ]]; then
+        VERSION_NUMBER=$((21 + (CURRENT_YEAR - 2025) * 2))
+    elif [[ ${CURRENT_MONTH} -ge 3 ]]; then
+        VERSION_NUMBER=$((21 + (CURRENT_YEAR - 2025) * 2 - 1))
+    else
+        VERSION_NUMBER=$((21 + (CURRENT_YEAR - 2026) * 2 ))
+    fi
+    echo "No version number provided. Using the version number ${VERSION_NUMBER} based on the current date."
+else
+    echo "Usage: $0 [VERSION_NUMBER]"
+    exit 1
+fi
 
 if [[ $(uname -s) == 'Darwin' ]] ; then  # macOS
     brew update || true
-    brew install flang
-    flang --version
+    brew install llvm flang clang lld  # The latest version will be installed, which is 21 in September 2025.
 else  # Assume Linux
 
     # Add the LLVM repository
@@ -19,35 +44,44 @@ else  # Assume Linux
     wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key \
         | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
 
-    # Install the packages; clang is needed.
+    # Install the packages (clang and lld are needed even if we use only flang).
     sudo apt update
-    sudo apt-get install -y flang-${VERSION_NUMBER} clang-${VERSION_NUMBER} # lld-${VERSION_NUMBER}
+    sudo apt-get install -y llvm-${VERSION_NUMBER} flang-${VERSION_NUMBER} clang-${VERSION_NUMBER}  lld-${VERSION_NUMBER}
 
     # Verify the installation
-    type flang-${VERSION_NUMBER} || \
-        { echo "flang-${VERSION_NUMBER} not found after the installation, which probably failed." >&2 ; exit 1; }
+    for TOOL in flang clang lld; do
+        type ${TOOL}-${VERSION_NUMBER} > /dev/null 2>&1 || \
+            { echo "${TOOL}-${VERSION_NUMBER} not found after the installation, which probably failed." >&2 ; exit 1; }
+    done
 
     # Set up a symbolic link named flang pointing to flang-${VERSION_NUMBER}
-    FLANG_DIR="$(dirname "$(which flang-${VERSION_NUMBER})")"
-    cd "$FLANG_DIR" || exit 1
-    if [[ -f flang ]]; then
-        echo "A flang executable already exists in the same directory as flang-${VERSION_NUMBER}."
-        echo "Its version is:"
-        flang --version
-        echo "Backing up the existing flang executable to flang.bak"
-        sudo mv flang flang.bak
-    fi
-    echo "Creating a symbolic link named flang pointing to flang-${VERSION_NUMBER} in $(pwd)"
-    sudo ln -s flang-${VERSION_NUMBER} flang
+    for TOOL in flang clang lld; do
+        TOOL_DIR="$(dirname "$(which ${TOOL}-${VERSION_NUMBER})")"
+        cd "$TOOL_DIR" || exit 1
+        if [[ -f ${TOOL} ]]; then
+            echo "A ${TOOL} executable already exists in ${TOOL_DIR}, the directory of ${TOOL}-${VERSION_NUMBER}."
+            echo "Its version is:"
+            ${TOOL} --version
+            echo "Backing up the existing ${TOOL} executable to ${TOOL}.bak"
+            sudo mv ${TOOL} ${TOOL}.bak
+        fi
+        echo "Creating a symbolic link named ${TOOL} pointing to ${TOOL}-${VERSION_NUMBER} in $(pwd)"
+        sudo ln -s ${TOOL}-${VERSION_NUMBER} ${TOOL}
+    done
 
 fi
 
-type flang > /dev/null 2>&1 || \
-    { echo "flang not found after the installation, which probably failed." >&2 ; exit 1; }
+# Verify installation
+for TOOL in flang clang lld; do
+    type $TOOL > /dev/null 2>&1 || \
+        { echo "$TOOL not found after the installation, which probably failed." >&2 ; exit 1; }
+done
 
 # Final messages
-echo "flang installation completed."
-echo -e "\nThe flang version is:\n"
-flang --version
-echo -e "\nThe path to flang is:\n"
-command -v flang
+echo "LLVM installation completed."
+for TOOL in flang clang lld; do
+    echo -e "\nThe $TOOL version is:\n"
+    $TOOL --version
+    echo -e "\nThe path to $TOOL is:\n"
+    command -v $TOOL
+done
