handle windows

diff --git a/.github/workflows/flang_heap_arrays.yml b/.github/workflows/flang_heap_arrays.yml
--- a/.github/workflows/flang_heap_arrays.yml
+++ b/.github/workflows/flang_heap_arrays.yml
@@ -18,7 +18,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-latest, macos-15-intel]
+        os: [ubuntu-latest, ubuntu-24.04-arm, macos-lates, macos-15-intel, windows-latest, windows-11-arm]
         compiler: [armflang, amdflang, flang]  # Compilers to test
         flag: [mmlir, fno-stack-arrays]  # Optimization flags to test
         exclude:
@@ -60,7 +60,7 @@ jobs:
       - name: Install LLVM Flang
         shell: bash
         if: matrix.compiler == 'flang'
-        run: bash ./install_llvm
+        run: bash ./install_llvm || { echo "Warning: LLVM Flang installation failed!!" >&2; exit 0; }
 
       - name: Install gdb and git
         shell: bash
@@ -69,9 +69,19 @@ jobs:
             sudo apt update || true && sudo apt install -y gdb git
           elif [[ "$RUNNER_OS" == "macOS" ]]; then
             brew update || true && brew install gdb git
-          fi
+          fi  # The installation will fail on Windows as of Feb 2026
 
       - name: Conduct the test
         shell: bash
         run: |
+          if [[ "${{ matrix.os }}" == windows-latest ]] ; then
+            echo "We are on ${{ matrix.os }}. LLVM installed by choco may not provide flang."
+            LLVM_VERSION=$(llvm-config --version 2>/dev/null | cut -d '.' -f1)
+            echo "LLVM version: $LLVM_VERSION"
+            FLANG_PATH=$(command -v flang 2>/dev/null || echo "NOT_FOUND")
+            echo "Flang path: $FLANG_PATH"
+            if [[ "$LLVM_VERSION" -lt 22 && "$FLANG_PATH" == "NOT_FOUND" ]] ; then
+              echo "Warning: flang not found!! Skipping the test." >&2
+            exit 0
+          fi
           bash ./flang_heap_arrays ${{ matrix.compiler }} ${{ matrix.flag }}
