correct yml

diff --git a/.github/workflows/flang_heap_arrays.yml b/.github/workflows/flang_heap_arrays.yml
--- a/.github/workflows/flang_heap_arrays.yml
+++ b/.github/workflows/flang_heap_arrays.yml
@@ -60,7 +60,9 @@ jobs:
       - name: Install LLVM Flang
         shell: bash
         if: matrix.compiler == 'flang'
-        run: bash ./install_llvm || { echo "Warning: LLVM Flang installation failed!!" >&2; exit 0; }
+        run: |
+          bash ./install_llvm \
+            || { echo "Warning: LLVM Flang installation failed!!" >&2; exit 0; }
 
       - name: Install gdb and git
         shell: bash
